FROM hamzamerzic/meshlab
LABEL maintainer="Brendan Papadopoulos"

############################# -------- BEGINNING OF NINAI   --------#######################

ARG DEBIAN_FRONTEND=noninteractive

###############################################################################
# Install some optimization libraries (used by many libraries below)
RUN apt-get update && \
    apt-get install -y libopenblas-dev libatlas-base-dev libeigen3-dev && \
    export MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1   

###############################################################################
# Install Python 3
RUN apt-get update && \
    apt-get install -y python3.6python3-dev python3-pip python3-numpy python3-scipy \
        python3-matplotlib

#######################  CELII ADDED   ###############################
RUN pip3 install --upgrade pip
RUN apt-get -y install gcc g++
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
#######################  CELII ADDED STOP  ###############################

## Get dependencies
RUN apt-get update && \
    apt-get install -y build-essential cmake git pkg-config libgtk-3-dev \
                       libavcodec-dev libavformat-dev libswscale-dev \
    # To recompile CUDA we need an slightly older compiler (current is gcc 7)
#                       gcc-6 g++-6 \
    # Optional dependencies
                       libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
                       libxvidcore-dev libx264-dev libhdf5-dev ffmpeg
    # Camera support
#                      libdc1394-22-dev libv4l-devel # camera support


RUN apt-get install wget

# Install CaImAn
# Install dependencies
#RUN apt-get install -y python3-tk && \
#    pip3 install future cvxpy scikit-learn scikit-image tensorflow keras \
#                 peakutils \
    # Unused but required (imported in code)
#                 ipyparallel Cython h5py tqdm psutil

RUN apt-get install -y python3-tk && \
    pip3 install Cython h5py tqdm ipyparallel psutil peakutils

RUN apt-get install -y  autoconf automake libtool

###############################################################################
# Miscelaneous packages
RUN pip3 install git+https://github.com/datajoint/datajoint-python.git && \
    pip3 install git+https://github.com/atlab/scanreader.git && \
#    pip3 install git+https://github.com/cajal/bl3d.git && \
    pip3 install seaborn slacker imreg_dft pandas imageio
RUN apt-get install -y python3-git

# Optional
RUN apt-get install -y nano graphviz && \
    pip3 install nose2 jupyterlab


############################# -------- END UP NINAI   --------#######################

############################# -------- BEGINNING OF CHRISTOS CONTAINER   --------#######################

RUN apt-get -y update && \
    apt-get -y install graphviz libxml2-dev python3-cairosvg parallel

# CGAL Dependencies ########################################################
RUN apt-get -y install libboost-all-dev libgmp-dev libmpfr-dev libcgal-dev libboost-wave-dev libeigen3-dev
############################################################################

RUN pip3 install datajoint --upgrade
RUN pip3 install python-igraph xlrd


WORKDIR /src

RUN pip3 install ipyvolume jupyterlab statsmodels pycircstat nose
RUN pip3 install seaborn --upgrade
RUN pip3 install jgraph

#RUN add-apt-repository ppa:boost-latest/ppa
#RUN apt-get update

RUN apt-get -y install vim
RUN . /etc/profile
ADD ./CGAL /src/CGAL
RUN pip3 install -e /src/CGAL
#RUN pip3 install --user nodejs.
RUN apt-get install -y npm nodejs-legacy && \
    npm install -g configurable-http-proxy && \
    pip3 install jupyterhub dockerspawner jupyter_client


WORKDIR /notebooks

#add the cgal scripts
EXPOSE 8895

RUN mkdir -p /scripts
ADD ./jupyter/run_jupyter.sh /scripts/
ADD ./jupyter/jupyter_notebook_config.py /root/.jupyter/
ADD ./jupyter/custom.css /root/.jupyter/custom/
RUN chmod -R a+x /scripts

ENTRYPOINT ["/scripts/run_jupyter.sh"]




