FROM ubuntu:18.04
LABEL maintainer="Brendan Papadopoulos"
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get -y update && \
    apt-get -y install graphviz libxml2-dev python3-cairosvg parallel


RUN apt-get -y install python3.7
RUN apt -y install python3-pip
RUN pip3 install datajoint --upgrade
RUN pip3 install python-igraph xlrd


WORKDIR /src

RUN pip3 install ipyvolume jupyterlab statsmodels pycircstat nose
RUN pip3 install seaborn --upgrade
RUN pip3 install jgraph



RUN apt-get -y install vim
RUN . /etc/profile

RUN apt-get update && apt-get install -q -y \
    build-essential \
    python \
    python-numpy \
    git \
    g++ \
    libeigen3-dev \
    qt5-qmake \
    qtscript5-dev \
    libqt5xmlpatterns5-dev \
    libqt5opengl5-dev \
    assimp-utils \
    nano \
    xvfb \
    && rm -rf /var/lib/apt/lists/*



WORKDIR /

#add the cgal scripts
EXPOSE 8888

#add the cgal scripts
#RUN git clone https://github.com/sdorkenw/MeshParty.git
#WORKDIR /MeshParty
#RUN pip3 install . --upgrade

RUN pip3 install pykdtree trimesh 
RUN pip3 install sklearn pymeshfix

#------------ 8/4 NEW ADDED FOR CGAL, MESHLAB AND OTHER APPLICATIONS -----  #

#ADD /meshlab /meshlab
#COPY --from=hamzamerzic/meshlab ./README.md /meshlab/README.md
RUN apt-get -y update
#RUN apt-get -y install software-properties-common
#RUN add-apt-repository ppa:zarquon42/meshlab
#RUN apt-get -y update
RUN apt-get -y install meshlab

RUN apt-get -y update && \
    apt-get -y install graphviz libxml2-dev python3-cairosvg parallel

# CGAL Dependencies ########################################################
RUN apt-get -y install libboost-all-dev libgmp-dev libmpfr-dev libcgal-dev libboost-wave-dev libeigen3-dev
############################################################################


RUN apt-get -y install vim
RUN . /etc/profile
ADD ./CGAL /src/CGAL
RUN pip3 install -e /src/CGAL/cgal_segmentation
#RUN pip3 install -e /src/CGAL/cgal_skeleton

RUN pip3 install nose pycircstat scipy
