#!/bin/bash
python3 0_MultiSomaCentroidValidationVp4_DJ.py &
python3 1_MultiSomaCentroidValidationVp4_DJ.py &
python3 2_MultiSomaCentroidValidationVp4_DJ.py &
python3 3_MultiSomaCentroidValidationVp4_DJ.py &
python3 4_MultiSomaCentroidValidationVp4_DJ.py &
python3 5_MultiSomaCentroidValidationVp4_DJ.py &
python3 6_MultiSomaCentroidValidationVp4_DJ.py &
python3 7_MultiSomaCentroidValidationVp4_DJ.py &
python3 8_MultiSomaCentroidValidationVp4_DJ.py &
python3 9_MultiSomaCentroidValidationVp4_DJ.py &
python3 10_MultiSomaCentroidValidationVp4_DJ.py &
python3 11_MultiSomaCentroidValidationVp4_DJ.py &
python3 12_MultiSomaCentroidValidationVp4_DJ.py &
python3 13_MultiSomaCentroidValidationVp4_DJ.py &
python3 14_MultiSomaCentroidValidationVp4_DJ.py &
python3 15_MultiSomaCentroidValidationVp4_DJ.py &
python3 16_MultiSomaCentroidValidationVp4_DJ.py &
python3 17_MultiSomaCentroidValidationVp4_DJ.py &
python3 18_MultiSomaCentroidValidationVp4_DJ.py &
python3 19_MultiSomaCentroidValidationVp4_DJ.py &
